// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UPsh_SsOnc_JKgS7JqwYy5tGsBs4wuQ',
    appId: '1:256577778272:web:003e0c9ceb1b275b234905',
    messagingSenderId: '256577778272',
    projectId: 'notifications-7ae71',
    authDomain: 'notifications-7ae71.firebaseapp.com',
    storageBucket: 'notifications-7ae71.firebasestorage.app',
    measurementId: 'G-692LPTCD2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyeFjqNIpFcxREjsh368LxkO-5uab-vZM',
    appId: '1:256577778272:android:373e630e11fe9d87234905',
    messagingSenderId: '256577778272',
    projectId: 'notifications-7ae71',
    storageBucket: 'notifications-7ae71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVcE5wohBlsoGLXyNX8ZK1zvM-GvNoTY',
    appId: '1:256577778272:ios:4a1cee0b5ce6e03b234905',
    messagingSenderId: '256577778272',
    projectId: 'notifications-7ae71',
    storageBucket: 'notifications-7ae71.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVcE5wohBlsoGLXyNX8ZK1zvM-GvNoTY',
    appId: '1:256577778272:ios:4a1cee0b5ce6e03b234905',
    messagingSenderId: '256577778272',
    projectId: 'notifications-7ae71',
    storageBucket: 'notifications-7ae71.firebasestorage.app',
    iosBundleId: 'com.example.notifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0UPsh_SsOnc_JKgS7JqwYy5tGsBs4wuQ',
    appId: '1:256577778272:web:32592077871b5958234905',
    messagingSenderId: '256577778272',
    projectId: 'notifications-7ae71',
    authDomain: 'notifications-7ae71.firebaseapp.com',
    storageBucket: 'notifications-7ae71.firebasestorage.app',
    measurementId: 'G-C13Q43YZ1E',
  );
}
